
log:
  type: local
  loglevel: debug

aws:
  region: eu-central-1

weather:
  owm:
    url: https://api.openweathermap.org/data/2.5
    latitude: 48.3596240
    longitude: 11.3860876
    units: metric